cd macro-visit
sbt +publishLocal
cd ..
cd sangria-marshalling-api
sbt +publishLocal
cd ..
cd sangria-marshalling-testkit
sbt +publishLocal
cd ..
cd sangria-streaming-api
sbt +publishLocal
cd ..
cd sangria-argonaut
sbt +publishLocal
cd ..
cd sangria-ion
sbt +publishLocal
cd ..
cd sangria-spray-json
sbt +publishLocal
cd ..
cd sangria
sbt +publishLocal
cd ..
